trigger:
- trunk
- release/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  testProject: 'test/ArdoqFluentModels.Tests/ArdoqFluentModels.Tests.csproj'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: $(testProject)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    projects: $(testProject)
    arguments: '--no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: $(testProject)
    arguments: '--no-build --filter Category!=Integration --collect "Code coverage"'