trigger:
  tags:
    include:
    - v*.*.*

variables:
  buildProject: 'src/ModelMaintainer/ModelMaintainer.csproj'
  testProject: 'test/ModelMaintainer.Tests/ModelMaintainer.Tests.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: $(buildProject)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    projects: $(buildProject)
    arguments: '--no-restore'

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: $(buildProject)
    nobuild: true
    versioningScheme: 'off'

- task: NuGetCommand@2
  displayName: 'Publish NuGet package'
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: NuGetLibs